### ISSUE TITLE
Display timezone doesn't change when switching tabs

### ISSUE THREAD

**Issue by ddello32** [clubedaentrega/node-mongo-admin#19]
If the user has two open tabs and changes the display timezone on one of them, the displayed timezone in the other will not update but the option in the context menu will.

PS: To show the displayed timezone in the date string would also be good.

**Comment by sitegui** [comment]
Yikes, right. This happens because those options are kept as global state shared between tabs (ie, `localStorage`) and the code checks that global state [when rendering the context menu](https://github.com/clubedaentrega/node-mongo-admin/blob/8e80774feded79f748dd161d779615aeb416d27e/public/Query.js#L713-L718).

This can be fixed by checking the cell state (ie, `dataset`). This bug also affects binary data display.

PS: Could you elaborate on your second point (in another issue if possible)? In "Local date" mode, the value is rendered using the browser current Date&Time settings.
